In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('Preprocessed_Data.csv')

In [10]:
df.head()

Diseases  Child_related  Poisoning  Other_Light_Reasons  Months  \
0         0              0          0                    1       7   
1         0              0          0                    0       7   
2         0              0          0                    1       7   
3         1              0          0                    0       7   
4         0              0          0                    1       7   

   Day of Week  Transportation Expense  Distance to Work  Age  \
0            1                     289                36   33   
1            1                     118                13   50   
2            2                     179                51   38   
3            3                     279                 5   39   
4            3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [20]:
df['Absenteeism Time in Hours'].value_counts()

8      195
2      149
3      106
1       87
4       57
0       39
16      18
24      15
40       7
5        7
32       6
64       3
112      2
56       2
80       2
120      2
48       1
7        1
104      1
Name: Absenteeism Time in Hours, dtype: int64

In [11]:
df['Absenteeism Time in Hours'].median()

3.0

In [13]:
targets = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(), 1, 0)

In [14]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [15]:
targets.shape

(700,)

In [16]:
df['Excessive Absenteeism'] = targets

In [18]:
df.head(3)

Diseases  Child_related  Poisoning  Other_Light_Reasons  Months  \
0         0              0          0                    1       7   
1         0              0          0                    0       7   
2         0              0          0                    1       7   

   Day of Week  Transportation Expense  Distance to Work  Age  \
0            1                     289                36   33   
1            1                     118                13   50   
2            2                     179                51   38   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0

In [19]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [23]:
df.drop(['Absenteeism Time in Hours'], axis = 1, inplace=True)

In [24]:
df.shape

(700, 15)

In [27]:
df.iloc[:,:-1].head()

Diseases  Child_related  Poisoning  Other_Light_Reasons  Months  \
0         0              0          0                    1       7   
1         0              0          0                    0       7   
2         0              0          0                    1       7   
3         1              0          0                    0       7   
4         0              0          0                    1       7   

   Day of Week  Transportation Expense  Distance to Work  Age  \
0            1                     289                36   33   
1            1                     118                13   50   
2            2                     179                51   38   
3            3                     279                 5   39   
4            3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  
0                  239.554               30          0         2     1  
1                  239.554               31          0         1     0  
2                  239.554               31          0         0     0  
3                  239.554               24          0         2     0  
4                  239.554               30          0         2     1

In [28]:
unscaled_inputs = df.iloc[:,:-1]

## Standardize the data

In [29]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [30]:
data_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
scaled_inputs = data_scaler.transform(unscaled_inputs)

In [32]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [33]:
scaled_inputs.shape

(700, 14)

## Train_Test_Split

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          1.78021889, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -

In [39]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8)

/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [40]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [41]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


## Logistic Regression with Sklearn

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [44]:
reg = LogisticRegression()

In [45]:
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
reg.score(x_train, y_train)

0.7785714285714286

### Understanding the accuracy score

In [54]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,

In [55]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,

In [56]:
model_outputs == y_train

array([ True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [53]:
np.sum(model_outputs == y_train)/y_train.shape[0]

0.7785714285714286

In [52]:
y_train.shape[0]

560

### Log_Reg Parameters

In [58]:
reg.intercept_

array([-0.28350271])

In [59]:
reg.coef_

array([[ 2.066673  ,  0.35780541,  1.57744204,  1.42253411,  0.04782291,
        -0.20331846,  0.7829418 , -0.05094961, -0.30233066, -0.03756521,
         0.313743  , -0.04274446,  0.47783667, -0.39493253]])

In [63]:
np.transpose(reg.coef_)

array([[ 2.066673  ],
       [ 0.35780541],
       [ 1.57744204],
       [ 1.42253411],
       [ 0.04782291],
       [-0.20331846],
       [ 0.7829418 ],
       [-0.05094961],
       [-0.30233066],
       [-0.03756521],
       [ 0.313743  ],
       [-0.04274446],
       [ 0.47783667],
       [-0.39493253]])

In [60]:
unscaled_inputs.columns.values

array(['Diseases', 'Child_related', 'Poisoning', 'Other_Light_Reasons',
       'Months', 'Day of Week', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [61]:
feature_name = unscaled_inputs.columns.values

In [62]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                  Diseases     2.066673
1             Child_related     0.357805
2                 Poisoning     1.577442
3       Other_Light_Reasons     1.422534
4                    Months     0.047823
5               Day of Week    -0.203318
6    Transportation Expense     0.782942
7          Distance to Work    -0.050950
8                       Age    -0.302331
9   Daily Work Load Average    -0.037565
10          Body Mass Index     0.313743
11                Education    -0.042744
12                 Children     0.477837
13                     Pets    -0.394933

In [64]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.283503
1                  Diseases     2.066673
2             Child_related     0.357805
3                 Poisoning     1.577442
4       Other_Light_Reasons     1.422534
5                    Months     0.047823
6               Day of Week    -0.203318
7    Transportation Expense     0.782942
8          Distance to Work    -0.050950
9                       Age    -0.302331
10  Daily Work Load Average    -0.037565
11          Body Mass Index     0.313743
12                Education    -0.042744
13                 Children     0.477837
14                     Pets    -0.394933

In [65]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [68]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Diseases     2.066673    7.898501
3                 Poisoning     1.577442    4.842553
4       Other_Light_Reasons     1.422534    4.147618
7    Transportation Expense     0.782942    2.187899
13                 Children     0.477837    1.612582
2             Child_related     0.357805    1.430187
11          Body Mass Index     0.313743    1.368538
5                    Months     0.047823    1.048985
10  Daily Work Load Average    -0.037565    0.963132
12                Education    -0.042744    0.958156
8          Distance to Work    -0.050950    0.950327
6               Day of Week    -0.203318    0.816018
0                 Intercept    -0.283503    0.753141
9                       Age    -0.302331    0.739094
14                     Pets    -0.394933    0.673725

In [ ]:
"""
The model could further be developed and/or changed in order to deal with the interpretability of the dummy vars 
because they are not considered worthy interpreting having standardized. Please take a look at the following quora
discussion for further details.
https://www.quora.com/How-bad-is-it-to-standardize-dummy-variables

I also found it to be a bit awkward to apply the LogReg by categorizing the absenteeism hours in 2 categories.
Linear regression can also be tried after checking the LinReg assumptions, or any other ML models.

"""